version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - urlService
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@url.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # pgAdmin web UI accessible on http://localhost:5050
    depends_on:
      - db
    networks:
      - urlService
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  url-service:
    build: ../
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/url-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - urlService
volumes:
  postgres-data:
  pgadmin-data:

networks:
  urlService:
    name: urlService
